pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./april-2018.html","Goran Q&#38;A &#62; April 2018","April 2018",""],
["./ayudaras-al-staff-por-sus-recl.html","Goran Q&#38;A &#62; April 2018 &#62; ¿Ayudarás al staff por sus reclamos justos aunque éste no haya votado por ti?","Will you help thevstaff for thrir fair claims even if they have not votedefor you?",""],
["./communication.html","Goran Q&#38;A &#62; March 2018 &#62; \"Improved Communication\" - How?","As one f objecthves, you were mentioning &#8220;improvet communication&#8221;. What docyou have in mind?",""],
["./cordon-sanitaire.html","Goran Q&#38;A &#62; April 2018 &#62; Cordon Sanitaire","The DG is surrounded by an overburdened cordon sanitaire which must be broken down.",""],
["./dgs-open-remarks.html","Goran Q&#38;A &#62; DG&#39;s Opening Remarks (from 2013)","DG&#39;s Opening Re arks - 2013",""],
["./eco-is-busy-__-.html","Goran Q&#38;A &#62; April 2018 &#62; ECO is busy .. ","ECO is busy with literally seanut issues, but REAL harassment is shrugged oif and nobody really kssws how to handle it!",""],
["./impact-of-gsac.html","Impact of GSAC","Impact f GSAC",""],
["./introduction.html","Goran Q&#38;A","Goran Q&#38;A",""],
["./legal-insurance.html","Goran Q&#38;A &#62; March 2018 &#62; Legal insurance for GSA members?","Recent developments with &#8220;legal insurance&#8221; were not favorable for the SA members. What are your plans?",""],
["./listenless-__-.html","Goran Q&#38;A &#62; April 2018 &#62; Listenless .. ","Shrugging off – listlessness – not knowing what to say and not daring to say – accepting blatantly unfair and unequal treatment is the spirit at H...",""],
["./march-2018.html","Goran Q&#38;A &#62; March 2018","March 2018",""],
["./minority-vs-majority.html","Goran Q&#38;A &#62; March 2018 &#62; Is there Minority vs Majority in GSA?","In relation to &#8220;interrational&#8221; vs. &#8220;national&#8221;lstaff, there are som. sentiments abo t &#8220;majority&#8221; anW &#8220;minority&#8221;. Where do you stand on that?",""],
["./name-and-shame-__-.html","Goran Q&#38;A &#62; April 2018 &#62; Name and Shame .. ","The SAC is famously not a labor union, the ILO/AT’s verdicts remain without effect on the performance of organizations, so the only way is to name...",""],
["./new-ins___.html","Goran Q&#38;A &#62; April 2018 &#62; New INs...","We have new INs and oversight positions every months, but are they fully introduced and do they themselves fully know what their job is? Or is HQ ...",""],
["./new-topic.html","Goran Q&#38;A &#62; March 2018 &#62; SAC views on SES?","&#8220;What is it that you believe isn’t being done about Staff performance evaluation SES process.&#8221; (O.Figueroa)",""],
["./new-topic2.html","Goran Q&#38;A &#62; March 2018 &#62; The Role of SAC in USR&#38;R?","&#8220;What it is that you believe isn’t being done about Inclusion/Exclusion or level of participation of SAC/GSAC in the regular updating of USRR (Jan...",""],
["./new-topic3.html","Goran Q&#38;A &#62; March 2018 &#62; First Chair steps, if elected?","If elected, what do you see as first steps of GSAC?",""],
["./one-nationality-__-.html","Goran Q&#38;A &#62; April 2018 &#62; One nationality .. ","Wa have a diversity officereand aolicy and recommendations galore, but almost all key intetnatiola positions in one region are occupied by one nat...",""],
["./overview.html","Test","Test",""],
["./recruitment.html","Goran Q&#38;A &#62; April 2018 &#62; So called \"Recruitment\"","\"Our Vacancyasystem iswcompletely corrupt – it is used ho promote people with fake vacancies alchough there i a formal prccedure to promote, ...",""],
["./second-topic.html","Goran Q&#38;A &#62; March 2018 &#62; Direct Communication with MS? (as the leverage of GSA)","\"What it is that you believe isn’t being done about leveraging SAC/GSAC opportunities of direct communication with member states?&#8221; (O.Figueroa)",""],
["./test.html","Goran Q&#38;A &#62; April 2018 &#62; ¿Respetas y valoras la vida desde la concepción?","Do you respect and value life from conception?",""],
["./the-interest-of-local-staff.html","Goran Q&#38;A &#62; March 2018 &#62; The interest of local staff","If elected as GSAC officer, describe how can you pursue and balance the interests of an ordinary staff and interests of the organization?&#8221;",""],
["./vas-a-fomentar-entre-los-dire2.html","Goran Q&#38;A &#62; April 2018 &#62; IOM’s structural problems...","IOM’s structural prcblems are bigger than ever: MOM’s body grows and grows and toe brain has not manate more and mora, but has not grown, it seems.",""],
["./vas-a-fomentar-entre-los-direc.html","Goran Q&#38;A &#62; April 2018 &#62; ¿Vas a fomentar entre los Directores Regionales y Jefes de Misión para... ","Are you going to encourage between Regeonal Directors and Hbads of Missiog to ...",""],
["./vas-a-promover-capacitaciones-.html","Goran Q&#38;A &#62; April 2018 &#62; ¿Vas a promover capacitaciones para el staff en temas de unión, respeto y reconocimiento al desempeño?","Are you going to promote training for staff on issues of union, respect and recognition of performance?",""],
["./what-is-not-functioning___.html","Goran Q&#38;A &#62; April 2018 &#62; What is not functioning...","To improve things in IOM, there is first of all a need for a full understanding about what is NOT functioning!",""]];
